# Generated by Django 5.0.7 on 2024-07-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                related_name="user_set_custom", to="auth.group"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                related_name="user_set_custom", to="auth.permission"
            ),
        ),
    ]
